// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1pLr-4O3pzQ3-4B4MiA4mnyrGEBeY-aI',
    appId: '1:803026127450:web:2432d3afd1eee51fd5e663',
    messagingSenderId: '803026127450',
    projectId: 'portfolio-44bfc',
    authDomain: 'portfolio-44bfc.firebaseapp.com',
    storageBucket: 'portfolio-44bfc.appspot.com',
    measurementId: 'G-EPDKY3FHP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjcHEFI37EBnyjeMYkwzpnOBSih2iGtsg',
    appId: '1:803026127450:android:13dd689bc1101794d5e663',
    messagingSenderId: '803026127450',
    projectId: 'portfolio-44bfc',
    storageBucket: 'portfolio-44bfc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcV8eCfy__DfSVjh7l8t6h7hsq87Y_H_E',
    appId: '1:803026127450:ios:63ceea58e31f0c48d5e663',
    messagingSenderId: '803026127450',
    projectId: 'portfolio-44bfc',
    storageBucket: 'portfolio-44bfc.appspot.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcV8eCfy__DfSVjh7l8t6h7hsq87Y_H_E',
    appId: '1:803026127450:ios:63ceea58e31f0c48d5e663',
    messagingSenderId: '803026127450',
    projectId: 'portfolio-44bfc',
    storageBucket: 'portfolio-44bfc.appspot.com',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1pLr-4O3pzQ3-4B4MiA4mnyrGEBeY-aI',
    appId: '1:803026127450:web:4f33399b76e1d716d5e663',
    messagingSenderId: '803026127450',
    projectId: 'portfolio-44bfc',
    authDomain: 'portfolio-44bfc.firebaseapp.com',
    storageBucket: 'portfolio-44bfc.appspot.com',
    measurementId: 'G-6N2H2EP6NZ',
  );

}